# Generated by Django 2.1.8 on 2019-05-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='mainmenuname',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
    ]
